export const BASE_BUTTON = {
    BASKET_ADD: 'В корзину',
    REVIEWS_ADD: 'Оставить отзыв',
    FILTER_RESET: 'Сбросить',
    SEARCH: 'Поиск',
    ADDRESS_MARKER: 'Адреса магазинов',
    PICK_UP_ADDRESSES: 'Адреса для самовывоза',
    APPLY_CHANGES: 'Применить изменения',
    CREATE_SECTION: 'Создать раздел',
    ADD_SECTION: 'Добавить раздел',
    DELETE_SECTION: 'Удалить раздел',
    ADD_FIELD: 'Добавить поле',
    DELETE_FIELD: 'Удалить поле',
    USER_LOGIN: 'Войти в аккаунт',
    USER_REGISTER: 'Создать аккаунт',
    USER_LOGOUT: 'Выйти',
    REVIEWS_CREATE: 'Опубликовать',
    CATALOG: "Каталог",
    DOWNLOAD_JSON: 'Загрузить файл данных',
    RESET_FORM: 'Сбросить форму',
    ADD_PRODUCT: 'Добавить товар',
    OK: 'Хорошо',
    REJECTION: 'Нет',
    ACCEPT: 'Да',
}