import { BASE_BUTTON, EMPTY_CONTENT, INPUT_CONTENT } from '../C'


export const SEARCH_COMPONENT = {
    INPUT_PLACEHOLDER: INPUT_CONTENT.SEARCH.PLACEHOLDER,
    BUTTON_SEARCH: BASE_BUTTON.SEARCH,
    EMPTY_RESULT: EMPTY_CONTENT.NOTHING_WAS_FOUND
}
